### ISSUE TITLE
焦点移动上去之后 item内容重叠是什么 有一个和item一样的 但是 大一点的 覆盖在上面

### ISSUE THREAD

**Issue by LxzBUG** [henryblue/TvRecyclerView#10]

**Comment by henryblue** [comment]
这时为了避免item获取焦点放大后, 被周围的item或布局遮挡, 这里我采用的是新建一个图层, 然后在上面将item画出来, 具体可以看代码. 这是在自动处理焦点的模式下的处理方式. 在不自动处理焦点模式下的处理方式具体看下面的连接或看源码
https://blog.csdn.net/lbcab/article/details/54576425

**Comment by LxzBUG** [comment]
好奇怪 我的item点击没用

**Comment by henryblue** [comment]
你可以结合使用场景分析, 或者是不是与开启软硬件加速有关
