### ISSUE TITLE
输入法导致焦点错乱

### ISSUE THREAD

**Issue by chenxihoulang** [henryblue/TvRecyclerView#14]
在第一个页面中将某个列表中的item选中,有焦点框,然后进入第二个页面(有输入法弹起),关闭输入法后,返回第一个页面,这时候,第一个页面中的那个选中的item的焦点框向上移动了(有两个同样焦点item)
![aaa](https://user-images.githubusercontent.com/4724467/40304750-792db596-5d2a-11e8-9350-363fc8215a8c.png)

**Comment by henryblue** [comment]
没有复现问题, 我的测试是点击item进入另外的页面弹出键盘，退出页面后焦点没问题。
