### ISSUE TITLE
isAutoFocus documentation

### ISSUE THREAD

**Issue by kingargyle** [henryblue/TvRecyclerView#18]
I think some of the documentation is out of date.   if I set isAutoFocus to false, no focus is shown for the item that has focus (which I would expect), but because of this, the focusScale and focusDrawable don't display.     The only way I have gotten these to work is to have isAutoFocus set to true, and making shoure that the focusDrawable is just a drawable either a png, image, or a non Selector drawable.

If you want I can do a pull request to update the documentation.   I'll probably have one coming along to add the Directional Keys from a keyboard to what the view should respond to besides just the DPAD events.

**Comment by henryblue** [comment]
yes, if set isAutoFocus to false, the focusScale and focusDrawable will not work(This is explained in the documentation)， isAutoFoucus set to false indicates that RecyclerView does not handle the focus, the focus is left to the child view to handle, so the zoom and focus frame should be handed to the child view. so my example：
https://github.com/henryblue/TvRecyclerView/blob/master/app/src/main/java/com/app/tvrecyclerview/maulCarouselActivity.java
the zoom is "FocusRelativeLayout" to handle.
My English is not good, maybe the document description is not clear

**Comment by kingargyle** [comment]
Yeah, that makes it more clear.   I'll try and get you a pull request this week, to help clarify it.   The view works well, once I figured things out.

**Comment by henryblue** [comment]
thank you very much
