### ISSUE TITLE
[Question] 控制focus框的出現和消失

### ISSUE THREAD

**Issue by RX1226** [henryblue/TvRecyclerView#25]
版大您好, 
想請問要如何控制focus框的出現和消失
如果我在選取時設定TvRecyclerView.setVisibility(View.GONE);
這時候畫面會留下選取的focus框
反之
如果用TvRecyclerView.setVisibility(View.VISIBLE);
則選取框不會一開始就出現在目標位置
這邊我用rcr.requestChildFocus(rcr.getNextFocusView(), rcr.getNextFocusView());
可以讓選取視窗顯示
不知道是否有正確的用法可以來控制focus選取框
謝謝大大了~

**Comment by henryblue** [comment]
如果isAutoProcessFocus属性为true，那么焦点框是单独处理的，因为这时焦点是有RecyclerView来处理，焦点不给子view， 只提供了换焦点框背景的接口
如果isAutoProcessFocus为true，焦点是交给子view的，RecyclerView不处理焦点（只修改了绘制顺序），如果想显示焦点，只能在子view中处理

按照你的需求， 你可以使用第二种方式， 不过焦点框需要自己在子view中处理， 两种模式代码例子中都有， 可以参考例子

**Comment by RX1226** [comment]
謝謝大大指導
有用第二種方式試出關閉時取消focus框
但是變成展開時沒辦法自動到指定位置並且秀出focus框
並且focus框的預設drawable變成無法顯現
必須要按一下方向鍵才有辦法再次出現focus框
不知道我是否有地方沒有設定好
謝謝大大指點了

**Comment by henryblue** [comment]
你可以试试setSelected接口
