### ISSUE TITLE
notifyDataSetChanged焦点丢失

### ISSUE THREAD

**Issue by sunxu3074** [henryblue/TvRecyclerView#26]
- 当我想改变view的UI展示时，发现只有onBIndViewHolder后才会有效果(滚动下去再滚动回来效果才会展示出来)。
- 于是我调用了 ___mAdapter.notifyDataSetChanged();
                    mTvRecyclerView.setItemSelected(position);___
- 当调用第一句代码时，recyclerview会丢失选中的装填。第二句position是对的，但还是会默认选中第一个。

**Comment by henryblue** [comment]
这些是基本功能， 不知道你是如何使用的， 应该不会有问题

**Comment by sunxu3074** [comment]
尝试调用  ___mAdapter.notifyItemChanged(position);___  ，但item后会显示一个原始大小的item与放大的并存，滚动时原始的会不动放在图层的最后边。

**Comment by henryblue** [comment]
这样就清楚了， 我最近会看一下

**Comment by sunxu3074** [comment]
好滴 谢谢 💂

**Comment by henryblue** [comment]
mAdapter.notifyItemChanged(position); 这句是起作用, 没有问题， 焦点也没问题（都是在原先选中的位置）不管焦点是否在需要改变的item上都没有问题，你看一下你用的是否有问题

**Comment by sunxu3074** [comment]
![446031540794100_ pic](https://user-images.githubusercontent.com/9284055/47632673-11785700-db86-11e8-92e7-b3fa3c64fab7.jpg)
![446041540794128_ pic](https://user-images.githubusercontent.com/9284055/47632678-13dab100-db86-11e8-9aad-89837b2823b8.jpg)

**Comment by sunxu3074** [comment]
- 第一张是点击后的效果
- 第二章是滚动的效果 第一课点击后一直在图层后

**Comment by henryblue** [comment]
这并不是mAdapter.notifyItemChanged(position)的问题， 如果你看源码了解默认焦点框的实现逻辑，就知道这是焦点框逻辑导致的问题， 为了方便放大选中与管理焦点框， 焦点框是单独处理并位于单独的图层， 换句话说就是在recyclerview上画一个焦点框，这样就会导致一个问题， 如果item背景是透明的，那么就会导致这个问题， 焦点框与下面的item重叠（就是透过焦点框看到下面的item）， 这并不是一个问题。 与实现逻辑有关， 有两种解决方案：
1. 将itemView设置一个背景（如果可以）， 可以解决这个问题
2.  使用第二种模式（不是默认的模式）将isAutoProcessFocus设置false（就是将焦点给子view来处理）， 自己自定义一个itemView来去实现放大缩小动画（或画焦点框）， 具体可以参考例子
https://github.com/henryblue/TvRecyclerView/blob/master/app/src/main/java/com/app/tvrecyclerview/maulCarouselActivity.java 
https://github.com/henryblue/TvRecyclerView/blob/master/app/src/main/java/com/app/tvrecyclerview/view/FocusRelativeLayout.java

**Comment by sunxu3074** [comment]
试了上面的都不管用，这个和#10 是一样的问题。如果有时间我加你qq吧，麻烦了
