### ISSUE TITLE
如果View剛好填滿畫面則無法左右移

### ISSUE THREAD

**Issue by RX1226** [henryblue/TvRecyclerView#27]
大大您好,
在使用時遇到一個問題
假設我有18個item, 但畫面一次只能顯示15個
如果我將物件大小調成最右邊一排會被切半
則可以順利往畫面右邊
如果item剛好每一個都可以完整呈現在畫面上
則在最右邊時, 按下方向右則無法位移
用debug去看是在
dispatchKeyEvent內
mNextFocused = FocusFinder.getInstance().findNextFocus(this, mSelectedItem, View.FOCUS_RIGHT);
的mNextFocused 會是null
不知道該如何解決
能否請大大指導一下
謝謝您了

**Comment by henryblue** [comment]
使用最新1.1.7版本

**Comment by RX1226** [comment]
謝謝大大, 這版本有解決了, 畫面再回去時會自動回到一半的位置
雖然FlyView會顯示完整的框, 而其他的會被切半
但還是有解決螢幕卡住的問題
謝謝大大的更新
