### ISSUE TITLE
Scroll is too slow

### ISSUE THREAD

**Issue by droid-wise** [henryblue/TvRecyclerView#29]
I have a requirement that recyclerview shouldn't be focused on evrey dpad down or dpad up pressed. User when pressing dpad down or up, it is going slow and on every item inside recyclerview, method onFocused is being called and in my case epg list is being downloaded. I want from user to be able to fast scroll down when pressing dpad and when he stops, right then download epg list. Sorry for my english, however I hope you will understand what I am saying.

**Comment by henryblue** [comment]
我不是很明白你的意思

**Comment by henryblue** [comment]
Do you mean that sliding slowly when you press key long?

**Comment by droid-wise** [comment]
It doesn't pass fast all items. It is going slow when you hold down key D-pad Down on remote control. You can see that it has to focus every next item and I want this case, when user hold down key D-pad down or D-pad up, it would fast pass all items inside list and when he stops, than the method for onFocused will be called.

**Comment by henryblue** [comment]
ok, you can test for 1.2.1 version

**Comment by droid-wise** [comment]
But in that version maybe setItemSelected() doesn't center item?

**Comment by droid-wise** [comment]
#28 see here

**Comment by henryblue** [comment]
it only select item not visible that will be slide center, please see my note
