### ISSUE TITLE
How to change text color on onItemViewFocusChanged?

### ISSUE THREAD

**Issue by grahaisw** [henryblue/TvRecyclerView#34]
Hi i'm getting stuck on this, i need to change the text color of my item when getting focus.

I have try onFocusChange on my CustomViewHolder, but nothing happen when the focus is changed.

Can anybody help?is it possible to change the element text color on onItemViewFocusChanged?

Thank you in advance.

**Comment by henryblue** [comment]
yes, you can change text color on "onItemViewFocusChanged"
Because the default Recyclerview will consume the focus, if you want to change in you customViewHolder, you can make isAutoProcessFocus attr false.
