### ISSUE TITLE
这种修改后，效果很差

### ISSUE THREAD

**Issue by renwfy** [henryblue/TvRecyclerView#4]
GridLayoutManager manager = new GridLayoutManager(NormalFocusActivity.this, 3);
manager.setOrientation(LinearLayoutManager.HORIZONTAL);
mTvRecyclerView.setLayoutManager(manager);

这里要是改为

 GridLayoutManager manager = new GridLayoutManager(NormalFocusActivity.this, 6);
 manager.setOrientation(LinearLayoutManager.VERTICAL);
mTvRecyclerView.setLayoutManager(manager);

效果很差那

**Comment by henryblue** [comment]
这是肯定的, 例子中的UI都是根据3行来调整的, 你设置成6行, 肯定效果不好. 首先, RecyclerView只是容器, 具体显示效果, 需要外部来适配(调整item的大小, layoutManager, focus drawable).
