### ISSUE TITLE
why

### ISSUE THREAD

**Issue by ghost** [henryblue/TvRecyclerView#5]
![qq 20170906143813](https://user-images.githubusercontent.com/13541599/30097615-1144ab3a-9311-11e7-8af0-a6054b4926a1.png)

**Comment by henryblue** [comment]
The reason for this problem is call getAdapter().getItemCount() in onLayout, the getAdapter maybe null, so i will fix this issue in next version. you can try to setAdapter after create TvRecyclerView.

**Comment by henryblue** [comment]
you can use 1.0.6 version
