### ISSUE TITLE
Next focus (left, right) is null

### ISSUE THREAD

**Issue by chuoichien** [henryblue/TvRecyclerView#7]
I have a recyclerview (Vertical layout) contain 100 recyclerview.
1. Focus on first item in first recyclerview (or any recyclerview in vertical list)
2. Keypress (Right) 

[http://2.pik.vn/201833a1a4cf-4b07-485a-a8aa-fb667fce4ec6.png](url)

Thanks for your support

**Comment by henryblue** [comment]
Link failure
